### ISSUE TITLE
Test using `POSTMARK_API_TEST` as the API key

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-postmark#2]
The `POSTMARK_API_TEST` key allows the mocking of sent emails.  The tests need to be written to use this.

**Comment by daffl** [comment]
This is probably why #3 is failing.

**Comment by marshallswain** [comment]
Closed in https://github.com/feathersjs/feathers-postmark/commit/02797632cc414359aaba0ca65bdf9c0c01145bf7
